create table cards (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	word VARCHAR(50) NOT NULL,
	meaning VARCHAR(50) NOT NULL
);
insert into cards (word, meaning) values ('Killer whale', 'Orcinus orca');
insert into cards (word, meaning) values ('Northern phalarope', 'Phalaropus lobatus');
insert into cards (word, meaning) values ('Red sheep', 'Ovis ammon');
insert into cards (word, meaning) values ('Egret, snowy', 'Egretta thula');
insert into cards (word, meaning) values ('Bird, bare-faced go away', 'Lorythaixoides concolor');
insert into cards (word, meaning) values ('Jackal, asiatic', 'Canis aureus');
insert into cards (word, meaning) values ('Black-crowned night heron', 'Nycticorax nycticorax');
insert into cards (word, meaning) values ('Iguana, land', 'Conolophus subcristatus');
insert into cards (word, meaning) values ('Shark, blue', 'Prionace glauca');
insert into cards (word, meaning) values ('Spectacled caiman', 'Caiman crocodilus');
insert into cards (word, meaning) values ('Gerenuk', 'Litrocranius walleri');
insert into cards (word, meaning) values ('Bateleur eagle', 'Terathopius ecaudatus');
insert into cards (word, meaning) values ('Heron, grey', 'Ardea cinerea');
insert into cards (word, meaning) values ('Brazilian otter', 'Pteronura brasiliensis');
insert into cards (word, meaning) values ('Caribou', 'Rangifer tarandus');
insert into cards (word, meaning) values ('Fox, arctic', 'Alopex lagopus');
insert into cards (word, meaning) values ('Crab, red lava', 'Graspus graspus');
insert into cards (word, meaning) values ('Frogmouth, tawny', 'Podargus strigoides');
insert into cards (word, meaning) values ('Antelope, four-horned', 'Tetracerus quadricornis');
insert into cards (word, meaning) values ('Red-billed tropic bird', 'Phaethon aethereus');
insert into cards (word, meaning) values ('Brown antechinus', 'Antechinus flavipes');
insert into cards (word, meaning) values ('Campo flicker', 'Colaptes campestroides');
insert into cards (word, meaning) values ('Black-fronted bulbul', 'Pycnonotus nigricans');
insert into cards (word, meaning) values ('Caribou', 'Rangifer tarandus');
insert into cards (word, meaning) values ('Red-shouldered glossy starling', 'Lamprotornis nitens');
insert into cards (word, meaning) values ('Lizard (unidentified)', 'unavailable');
insert into cards (word, meaning) values ('Coqui partridge', 'Francolinus coqui');
insert into cards (word, meaning) values ('Sloth, pale-throated three-toed', 'Bradypus tridactylus');
insert into cards (word, meaning) values ('Cougar', 'Felis concolor');
insert into cards (word, meaning) values ('Black-crowned crane', 'Balearica pavonina');
insert into cards (word, meaning) values ('Curve-billed thrasher', 'Toxostoma curvirostre');
insert into cards (word, meaning) values ('Lizard, frilled', 'Chlamydosaurus kingii');
insert into cards (word, meaning) values ('Lemming, arctic', 'Dicrostonyx groenlandicus');
insert into cards (word, meaning) values ('Buffalo, american', 'Bison bison');
insert into cards (word, meaning) values ('Jaeger, long-tailed', 'Stercorarius longicausus');
insert into cards (word, meaning) values ('African bush squirrel', 'Paraxerus cepapi');
insert into cards (word, meaning) values ('Brocket, red', 'Mazama americana');
insert into cards (word, meaning) values ('Seal, southern elephant', 'Mirounga leonina');
insert into cards (word, meaning) values ('Devil, tasmanian', 'Sarcophilus harrisii');
insert into cards (word, meaning) values ('African black crake', 'Limnocorax flavirostra');
insert into cards (word, meaning) values ('Wallaby, red-necked', 'Macropus rufogriseus');
insert into cards (word, meaning) values ('Pintail, bahama', 'Anas bahamensis');
insert into cards (word, meaning) values ('American woodcock', 'Scolopax minor');
insert into cards (word, meaning) values ('Lion, galapagos sea', 'Zalophus californicus');
insert into cards (word, meaning) values ('Brush-tailed phascogale', 'Phascogale tapoatafa');
insert into cards (word, meaning) values ('Barbet, crested', 'Trachyphonus vaillantii');
insert into cards (word, meaning) values ('Civet cat', 'Bassariscus astutus');
insert into cards (word, meaning) values ('Potoroo', 'Potorous tridactylus');
insert into cards (word, meaning) values ('Common zebra', 'Equus burchelli');
insert into cards (word, meaning) values ('Ibis, glossy', 'Plegadis falcinellus');
insert into cards (word, meaning) values ('Deer, roe', 'Capreolus capreolus');
insert into cards (word, meaning) values ('Dove, ring', 'Columba palumbus');
insert into cards (word, meaning) values ('Swamp deer', 'Cervus duvauceli');
insert into cards (word, meaning) values ('Racer, blue', 'Coluber constrictor foxii');
insert into cards (word, meaning) values ('Land iguana', 'Conolophus subcristatus');
insert into cards (word, meaning) values ('Asian foreset tortoise', 'Manouria emys');
insert into cards (word, meaning) values ('Tortoise, radiated', 'Geochelone radiata');
insert into cards (word, meaning) values ('Coqui francolin', 'Francolinus coqui');
insert into cards (word, meaning) values ('Hudsonian godwit', 'Limosa haemastica');
insert into cards (word, meaning) values ('Toddy cat', 'Paradoxurus hermaphroditus');
insert into cards (word, meaning) values ('Rhesus monkey', 'Macaca mulatta');
insert into cards (word, meaning) values ('Python, carpet', 'Morelia spilotes variegata');
insert into cards (word, meaning) values ('Owl, burrowing', 'Speotyte cuniculata');
insert into cards (word, meaning) values ('Owl, australian masked', 'Tyto novaehollandiae');
insert into cards (word, meaning) values ('Dassie', 'Dendrohyrax brucel');
insert into cards (word, meaning) values ('Lion, south american sea', 'Otaria flavescens');
insert into cards (word, meaning) values ('Iguana, common green', 'Iguana iguana');
insert into cards (word, meaning) values ('Caiman, spectacled', 'Caiman crocodilus');
insert into cards (word, meaning) values ('Bulbul, black-eyed', 'Pycnonotus barbatus');
insert into cards (word, meaning) values ('Least chipmunk', 'Eutamias minimus');
insert into cards (word, meaning) values ('Saddle-billed stork', 'Ephipplorhynchus senegalensis');
insert into cards (word, meaning) values ('Hyrax', 'Dendrohyrax brucel');
insert into cards (word, meaning) values ('Puma', 'Felis concolor');
insert into cards (word, meaning) values ('Baboon, chacma', 'Papio ursinus');
insert into cards (word, meaning) values ('Ring-necked pheasant', 'Phasianus colchicus');
insert into cards (word, meaning) values ('Eastern grey kangaroo', 'Macropus giganteus');
insert into cards (word, meaning) values ('Cliffchat, mocking', 'Thamnolaea cinnmomeiventris');
insert into cards (word, meaning) values ('Opossum, american virginia', 'Didelphis virginiana');
insert into cards (word, meaning) values ('Jackal, indian', 'Canis aureus');
insert into cards (word, meaning) values ('Wildebeest, blue', 'Connochaetus taurinus');
insert into cards (word, meaning) values ('Little brown bat', 'Myotis lucifugus');
insert into cards (word, meaning) values ('Wallaby, whip-tailed', 'Macropus parryi');
insert into cards (word, meaning) values ('Jackal, asiatic', 'Canis aureus');
insert into cards (word, meaning) values ('Dove, rock', 'Columba livia');
insert into cards (word, meaning) values ('Red-winged hawk (unidentified)', 'unavailable');
insert into cards (word, meaning) values ('Savanna fox', 'Dusicyon thous');
insert into cards (word, meaning) values ('Yellow baboon', 'Papio cynocephalus');
insert into cards (word, meaning) values ('Otter, giant', 'Pteronura brasiliensis');
insert into cards (word, meaning) values ('Yellow-bellied marmot', 'Marmota flaviventris');
insert into cards (word, meaning) values ('Pelican, brown', 'Pelecanus occidentalis');
insert into cards (word, meaning) values ('European badger', 'Meles meles');
insert into cards (word, meaning) values ('Common brushtail possum', 'Trichosurus vulpecula');
insert into cards (word, meaning) values ('Leopard', 'Panthera pardus');
insert into cards (word, meaning) values ('Capuchin, white-fronted', 'Cebus albifrons');
insert into cards (word, meaning) values ('Hartebeest, red', 'Alcelaphus buselaphus caama');
insert into cards (word, meaning) values ('Rhea, common', 'Rhea americana');
insert into cards (word, meaning) values ('Waxbill, violet-eared', 'Uraeginthus granatina');
insert into cards (word, meaning) values ('Beaver, north american', 'Castor canadensis');
insert into cards (word, meaning) values ('Cape Barren goose', 'Cereopsis novaehollandiae');
insert into cards (word, meaning) values ('Red-cheeked cordon bleu', 'Uraeginthus bengalus');